require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.6
  # SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 30

Metrics/AbcSize:
  Max: 40
